# Generated by Django 4.2.7 on 2025-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
