# Generated by Django 4.2.7 on 2025-10-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_userprofile_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='celular',
            field=models.CharField(blank=True, max_length=10, verbose_name='Teléfono'),
        ),
    ]
